### ISSUE TITLE
Hide smooch button

### ISSUE THREAD

**Issue by brene** [smooch/smooch-js#392]
I wish there is a method that allows me to hide the action button. Because is smaller views I want to implement my custom widget opener. I imagine calling `Smooch.hide()` it'll just hide the button but if I call `Smooch.open()` from some other code it'll open the conversation view.

**Comment by lemieux** [comment]
Hey @brene,

you can force the button to hide by adding something like this to your stylesheet.

```css
#sk-holder #sk-messenger-button {
    display: none;
}
```

Hope this helps!
